colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Festival VIP
layout_spectrum: 0.5295576765201986
typography_spectrum: 0.03784945793449879
color:
  brandStrength: 0.43329268996603787
  lightness: 0.20341365551576018
  saturation: 0.41505198017694056
  rhythmicContrast: 0.21025802777148783
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/0c4b9a3f-6ff2-4df0-aa28-5e0c8631997d.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/0c4b9a3f-6ff2-4df0-aa28-5e0c8631997d.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: Welcome To The First Decentralized Festival Ticket Market
description: Buy Festival Tickets With Crypto For Your Favorite Festivals
author:
  name: Crypto Wizard
  email: wizard@festival.vip
purpose:
  - type: external
    url: 'https://wallet.bitshares.org/?r=festival-vip'
    label: CREATE YOUR ACCOUNT TODAY
github: true
